### PR TITLE
1 as a client i would like to receive a list with all the users

### LINKED ISSUE #1: As a client I would like to receive a list with all the users
**Description**
Generate an API call for receiving a user list.

**Example**

> _Happy path:_

> - Request: GET /api/users/list

> - Response: 200 OK

```

[{id: ‘1’}, {id: ‘2’}, {id:’3’}]

```

> _There aren't users:_

> - Request: GET /api/users/list

> - Response: 200 OK

```
[]
```

> _Generic error:_

> - Request: GET /api/users/list

> - Response: 400 Bad Request

```
{ 'error' : ‘Hubo un error al realizar la petición’}
```

### PR DESCRIPTION
**Pull request by claverdb**
**Resolves**
Resolve #1

### CODE REVIEW

File: tests/app/Infrastructure/Controller/GetUsersListControllerTest.php [hunk 1]
```diff
@@ -27,16 +27,54 @@ protected function setUp(): void
...
         $this->userDataSource
-            ->expects('listAll')
-            ->never();
-            //->once();
+            ->expects('listedUsers')
+            ->once();
 
         $response = $this->get("/api/users/list");
 
         $response->assertExactJson([]);
```
Comment (oihanaelizagoyen) [inline tests/app/Infrastructure/Controller/GetUsersListControllerTest.php]: Here is necessary a code status verification, add please.

**Review by oihanaelizagoyen — CHANGES_REQUESTED** [review]

File: tests/app/Infrastructure/Controller/GetUsersListControllerTest.php (hunk 1 above)
Comment (claverdb) [reply tests/app/Infrastructure/Controller/GetUsersListControllerTest.php]: Resolved

**Review by oihanaelizagoyen — APPROVED** [review]
